Repository oracle/oci-cloud-controller-manager, pull requests merged in 2018-04, with the labels that each got.

#169 Fixes #168 discover compartment id from metadata when not set in config
  pkg/oci/client/client.go
Labels: enhancement

#171 Move Config out of client pkg
  pkg/oci/ccm.go
  pkg/oci/client/client.go
  pkg/oci/client/compute.go
  pkg/oci/client/load_balancer.go
  pkg/oci/config.go
  pkg/oci/config_test.go
  pkg/oci/config_validate.go
  pkg/oci/config_validate_test.go
  pkg/oci/instances.go
  pkg/oci/load_balancer.go
  pkg/oci/zones.go
Labels: enhancement

#177 Fix panic when EnsureLoadBalancer() called with 0 nodes
  pkg/oci/load_balancer.go
  pkg/oci/load_balancer_spec.go
  pkg/oci/load_balancer_spec_test.go
Labels: bug

#180 Frontend-only security list management and explicit security list config
  manifests/cloud-provider-example.yaml
  pkg/oci/ccm.go
  pkg/oci/config.go
  pkg/oci/config_validate.go
  pkg/oci/config_validate_test.go
  pkg/oci/load_balancer_security_lists.go
Labels: enhancement

#181 Support authentication via instance principals (#155)
  manifests/cloud-provider-example.yaml
  pkg/oci/ccm.go
  pkg/oci/config.go
  pkg/oci/config_validate.go
  pkg/oci/config_validate_test.go
Labels: enhancement

#187 Remove kubeadm.md from docs
  docs/kubeadm.md
Labels: documentation

#189 Add github issue template
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#191 Add note about upgrading the CCM
  README.md
Labels: documentation
