Repository oracle/oci-cloud-controller-manager, pull requests merged in 2018-08, with the labels that each got.

#229 update release version support matrix
  README.md
Labels: documentation

#201 Support request rate limiting
  README.md
  docs/rate-limiter-configuration.md
  pkg/oci/ccm.go
  pkg/oci/ccm_test.go
  pkg/oci/client/client.go
  pkg/oci/client/client_test.go
  pkg/oci/client/compute.go
  pkg/oci/client/errors.go
  pkg/oci/client/load_balancer.go
  pkg/oci/client/networking.go
  pkg/oci/config.go
  pkg/oci/config_test.go
Labels: enhancement, feature

#237 Update CHANGELOG for 0.6.0 release
  CHANGELOG.md
Labels: documentation

#239 Support load balancer listeners with http protocol via annotation
  docs/load-balancer-annotations.md
  pkg/oci/load_balancer.go
  pkg/oci/load_balancer_spec.go
  pkg/oci/load_balancer_spec_test.go
Labels: enhancement, feature

#238 Prevent leaking seclist ingress and egress rules when updating a service
  Makefile
  hack/boilerplate/boilerplate.py
  hack/test-e2e.sh
  pkg/oci/ccm.go
  pkg/oci/ccm_test.go
  pkg/oci/load_balancer.go
  pkg/oci/load_balancer_security_lists.go
  pkg/oci/load_balancer_security_lists_test.go
  test/e2e/README.md
  test/e2e/framework/framework.go
  test/e2e/framework/networking_util.go
  test/e2e/framework/seclist_util.go
  test/e2e/load_balancer.go
  wercker.yml
Labels: bug, enhancement
